[colors.bright]
black = "#7f7f7f"
blue = "#5c5cff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.normal]
black = "#000000"
blue = "#0000ee"
cyan = "#00cdcd"
green = "#00cd00"
magenta = "#cd00cd"
red = "#cd0000"
white = "#e5e5e5"
yellow = "#cdcd00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[env]
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 10.5

[font.normal]
family = "monospace"
style = "Regular"
